apiVersion: v1
data:
  mssql-sa-password: U2VhdHRsZTgwMA==
  username: c2E=
kind: Secret
metadata:
  name: sql-myhr-app-login-secret
  namespace: azure-arc-data
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: sql-myhr-app
  namespace: azure-arc-data
spec:
  limits:
    vcores: 4
  requests:
    vcores: 4
  service:
    type: NodePort
  storage:
    data:
      className: local-storage-data
      size: 100Gi
    logs:
      className: local-storage-logs
      size: 5Gi
