apiVersion: v1
data:
  password: WXVrb245MDBBcmMh
  username: YXJjLWFkbWlu
kind: Secret
metadata:
  name: sqlgitops1-login-secret
  namespace: azure-arc-data
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: sqlgitops1
  namespace: azure-arc-data
spec:
  limits:
    vcores: 4
  requests:
    vcores: 2
  service:
    type: NodePort
  storage:
    data:
      className: local-storage-data
      size: 15Gi
    logs:
      className: local-storage-logs
      size: 5Gi
    backups:
      className: local-storage-logs
      size: 30Gi
    datalogs:
      className: local-storage-data
      size: 15Gi
