apiVersion: v1
data:
  mssql-sa-password: U2VhdHRsZTgwMA==
  username: c2E=
kind: Secret
metadata:
  name: sqlgitops1-login-secret
  namespace: arc
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: sqlgitops1
  namespace: arc
spec:
  limits:
    vcores: 4
  requests:
    vcores: 2
  service:
    type: NodePort
  storage:
    data:
      className: local-storage-data
      size: 100Gi
    logs:
      className: local-storage-logs
      size: 5Gi
